[package]
name = "rust_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
helix-rs = "0.1.9"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.4", features = ["server"] }