[project]
name = "python"
version = "0.1.0"
description = "HelixDB Quickstart"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "helix-py>=0.2.27",
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
]
